try{
console.log(a);
let a = 3;}
catch (err){
    console.log("'let must be declared' before use")
}


try{
    let res = 1/0;
    if(isNaN(result)){
        throw new Error('cannot be divided by zero');
    }}
catch (error) {
        console.error(Error);
      }
    